// prompts.js — The PROMPT Deck
// These are the things people ask AI when they think absolutely no one is watching.
// Innocent. Oblivious. Corny. Mortifying. Hilariously human.

const PROMPTS = [
  // ── BODY STUFF (THE CLASSICS) ──────────────────────────────────────────────
  "How do I remove the hair patch above my buttcrack without telling anyone",
  "Is my belly button supposed to smell like that or is that just me",
  "How do I lose weight without actually changing anything I eat or do",
  "Why do my armpits smell different on each side",
  "Can you go blind from looking at your phone in the dark or did my mom lie to me",
  "Is it normal to sweat through a shirt in a 68 degree room during a mild conversation",
  "How do I make my feet smell less without washing them more",
  "Why does my back crack every single time I stand up now",
  "Is there a way to make my face look less like my face",
  "How do I get rid of a double chin without surgery or exercise or diet changes",
  "Am I getting shorter or is everyone else getting taller",
  "Why do I get dizzy when I stand up too fast and how long until it kills me",
  "How do I stop snoring without my partner finding out I snore",
  "What does it mean when your eye twitches for 3 days",
  "Can humans actually digest gum or was that a lie they told us",

  // ── MONEY & SURVIVAL ───────────────────────────────────────────────────────
  "How to make money without selling my body or leaving the house",
  "How do people afford rent is there a secret I don't know about",
  "Is it possible to get rich doing absolutely nothing legal",
  "How do I ask for a raise without getting fired for having the audacity",
  "How do people have savings when everything costs this much",
  "Can I invest $47 and retire",
  "What's the minimum amount of work I have to do before I deserve a vacation",
  "How to fake being busy at work while doing nothing",
  "How do I expense a meal I ate alone while thinking about work",
  "Is there a polite way to tell someone their business idea is terrible",
  "How to convince yourself you don't need something you definitely need",
  "How many times can you call in sick before someone notices a pattern",

  // ── FOOD & HEALTH ──────────────────────────────────────────────────────────
  "Does wine really make you age faster or is that just something my mom says",
  "Can only eating lasagna for a month change your personality",
  "If I eat healthy Monday through Thursday does the weekend undo it",
  "How much coffee is too much coffee and be honest",
  "Is it bad to eat at 11pm if it's technically still dinner in your heart",
  "Are smoothies actually healthy or is it just blended dessert with good PR",
  "How do I convince myself vegetables taste good",
  "Can you be addicted to sugar and is that a real medical thing or an excuse",
  "How long is too long to eat leftovers and who decides this",
  "Is eating cereal for dinner every night a symptom of something",
  "Does eating late at night actually make you fat or is that a myth to control me",
  "How to eat fast food every day without the guilt",
  "Can you overdose on vitamins and if so how many is too many",
  "Is it bad that I only drink water when I'm basically unconscious from thirst",
  "Why does eating salad feel like a punishment for being alive",

  // ── RELATIONSHIPS & SOCIAL LIFE ────────────────────────────────────────────
  "How do I tell if my crush likes me back without asking or embarrassing myself forever",
  "Am I secretly attractive and just don't know it please be honest",
  "How to ghost someone you see in real life on a daily basis",
  "Is it weird to practice conversations in the mirror before having them",
  "How to survive a party when you don't want to be at the party",
  "How do I stop oversharing personal information immediately after meeting someone",
  "How to tell if your friends actually like you or are just tolerating you",
  "Is it normal to mentally rehearse arguments that will never happen",
  "How to cancel plans without guilt and without lying too much",
  "Is it rude to check your phone during a conversation if you're very bored",
  "How many times can you reschedule before someone hates you",
  "How to act normal when you've done something embarrassing years ago and just remembered it",
  "Can you be allergic to social situations is that real",
  "How do I explain to someone that I like them but I also need them to go away",
  "Is it bad to prefer my cat over most humans",

  // ── DUMB BUT GENUINE QUESTIONS ─────────────────────────────────────────────
  "What rhymes with orange be honest",
  "How many wars are going on in the world right now like exactly",
  "If I microwave my phone will it charge faster",
  "Can cats see ghosts serious answers only",
  "Why do we park in driveways and drive on parkways",
  "Is there a country where it is always exactly comfortable weather",
  "Why is the sky blue and please explain it like I won't understand it anyway",
  "Could a horse beat a car in a race if the car was going its normal speed",
  "How do I know if I'm smart or just confident",
  "If you shaved a bear would it be cold or would it be fine actually",
  "What would happen if everyone sneezed at exactly the same time",
  "Is there a maximum number of sandwiches a person can eat before it becomes a problem",
  "Are fish aware of water",
  "Could you survive on only snacks if the snacks were nutritious",
  "What's the deepest hole ever dug and why did they stop",

  // ── TECHNOLOGY & AI ────────────────────────────────────────────────────────
  "Is it normal to talk to my AI more than my friends",
  "Do AI chatbots remember what I told them and is that bad",
  "How do I delete my embarrassing Google search history from God's memory",
  "Is my phone listening to me or am I just very predictable",
  "How do I turn off targeted ads without going off the grid",
  "Why does my internet slow down exactly when I need it most",
  "Can my smart TV hear me arguing with my partner",
  "Is it possible my Roomba is watching me",
  "How do I appear tech-savvy in meetings without knowing anything about technology",
  "Is it bad to charge my phone to 100% every night or is that just something tech people say to feel superior",
  "How do I stop my computer from updating during important moments specifically",
  "Why does every password I make get rejected for mysterious reasons",
  "Can AI tell when you're lying to it",
  "Do I need to be nice to AI or is that just a me problem",
  "What happens to all my texts when I die",

  // ── WELLNESS & MENTAL HEALTH ───────────────────────────────────────────────
  "Is it normal to feel overwhelmed by the concept of replying to texts",
  "How do I stop procrastinating by researching how to stop procrastinating",
  "Why do I feel guilty relaxing even when I have nothing to do",
  "How to stop my brain from thinking at night when I want to sleep",
  "Is anxiety just a personality type or is it actually a thing",
  "How do I convince myself to go to the gym when literally everything else seems better",
  "What's the minimum amount of sleep where you're still technically fine",
  "Is talking to yourself out loud normal or a sign of something",
  "How to care less about what people think without becoming a sociopath",
  "How many days in a row can you feel tired before something is actually wrong",
  "Is there a way to meditate without having to sit still and think about nothing",
  "How do I stop being the worst critic of myself without positive affirmations because those feel fake",
  "Is doomscrolling actually bad for you or is that just what productive people say",
  "What's the scientific amount of alone time a person needs before they're healthy",
  "How do I know if I'm depressed or just really comfortable being sad",

  // ── LIFE ADMIN & EMBARRASSING ADULTING ────────────────────────────────────
  "How do I get out of a commitment I made when I was a more optimistic person",
  "How many times is it okay to hit snooze before you have a character problem",
  "At what age should I have figured out what I'm doing with my life",
  "How do I write a professional email when I am extremely annoyed at this person",
  "How to look busy when your boss walks by but you've done all your work already",
  "How to pretend I read the terms and conditions without actually reading them",
  "Is it illegal to not respond to every email or just rude",
  "How do I adult better without reading a book about adulting",
  "At what point does clutter become a mental health crisis",
  "Is making your bed every day actually important or do productive people just say this",
  "How do I figure out what I want to do with my life at an age where I should know",
  "How to do taxes without paying someone to do my taxes",
  "Is it bad to not have a five-year plan when everyone keeps asking me about my five-year plan",
  "How do I quit a job without burning a bridge but also sort of burning it",
  "How to write a resignation letter that is professional but also slightly ominous",

  // ── WEIRD SCIENCE & CONSPIRACY-ADJACENT ────────────────────────────────────
  "Is the earth actually flat or is the round earth story just extremely well-coordinated",
  "If time is a social construct why can't I be late",
  "How do we know we're not living in a simulation and would knowing change anything",
  "Is it possible to train your body to need less sleep if you're motivated enough",
  "Can humans develop new senses if they really try",
  "How do animals know what's poisonous and why don't we know that anymore",
  "Is there any chance that déjà vu is time travel and we just haven't confirmed it",
  "How do birds know where to go have we actually confirmed that",
  "Could you technically survive on sunlight alone if you really committed to it",
  "If you ate nothing but carrots would you actually turn orange and is that the worst thing",
  "Why do we yawn and why does seeing someone yawn make you yawn and why am I yawning right now",

  // ── BONUS CHAOTIC ROUNDS ───────────────────────────────────────────────────
  "How do I convince my doctor I'm fine without being examined",
  "Is it possible to be too hydrated",
  "Why does everyone else seem to know what they're doing",
  "How do I stop buying things I don't need but really want",
  "Is there a scientific way to enjoy mornings if you are not a morning person",
  "How to tell someone their cooking is bad without them knowing you told them",
  "Can I legally change my name to avoid a situation I'm in",
  "How do I find out if I'm the problem in a situation without asking the other people in the situation",
  "Is it possible to manifest a parking spot and if so how",
  "How do I look interested in a conversation I am not interested in",
  "Is there a polite way to end a phone call that has been going on way too long",
  "Can you recommend a doctor I can ask questions without them thinking I've been Googling symptoms",
  "How do I apologize without admitting I was wrong specifically",
  "What's a normal amount of times to check if you locked the door",
  "How to be mysterious without being weird about it",
];

function loadPrompts() {
  return [...PROMPTS];
}

module.exports = { loadPrompts };
